név = input('Hogy hívnak téged? ')
születési_év = input('Mi a születési éved?')
csillagjegy = input('Mi a csillag jegyed?')
print('Szervusz ', név, ', örülök, hogy találkoztunk.', sep='')
print('születési idő: ',születési_év)
print('csillagjegy:',csillagjegy )